// marshal control plane and agent protocol.
//
// Regenerate with deploy/tools.sh gen-proto (protoc + protoc-gen-go +
// protoc-gen-go-grpc); generated code is committed under
// pkg/rpc/marshalpb so builds never require protoc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: marshal.proto

package marshalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillis     int64                  `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Gres          map[string]int64       `protobuf:"bytes,3,rep,name=gres,proto3" json:"gres,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_marshal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceSpec) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *ResourceSpec) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceSpec) GetGres() map[string]int64 {
	if x != nil {
		return x.Gres
	}
	return nil
}

type JobSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Request       *ResourceSpec          `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`                       // per node
	NodeCount     int32                  `protobuf:"varint,4,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"` // >1 = gang
	EstRuntimeMs  int64                  `protobuf:"varint,5,opt,name=est_runtime_ms,json=estRuntimeMs,proto3" json:"est_runtime_ms,omitempty"`
	Cmd           string                 `protobuf:"bytes,6,opt,name=cmd,proto3" json:"cmd,omitempty"` // shell command the agent executes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_marshal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{1}
}

func (x *JobSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *JobSpec) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobSpec) GetRequest() *ResourceSpec {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *JobSpec) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *JobSpec) GetEstRuntimeMs() int64 {
	if x != nil {
		return x.EstRuntimeMs
	}
	return 0
}

func (x *JobSpec) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type JobInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec           *JobSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	State          string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // PENDING/SCHEDULED/RUNNING/COMPLETED/FAILED/PREEMPTED
	Attempt        int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	SubmitAtUnixMs int64                  `protobuf:"varint,5,opt,name=submit_at_unix_ms,json=submitAtUnixMs,proto3" json:"submit_at_unix_ms,omitempty"`
	NodeIds        []string               `protobuf:"bytes,6,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // last known placement
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_marshal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{2}
}

func (x *JobInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobInfo) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *JobInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobInfo) GetSubmitAtUnixMs() int64 {
	if x != nil {
		return x.SubmitAtUnixMs
	}
	return 0
}

func (x *JobInfo) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type NodeInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity            *ResourceSpec          `protobuf:"bytes,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Allocated           *ResourceSpec          `protobuf:"bytes,3,opt,name=allocated,proto3" json:"allocated,omitempty"`
	LastHeartbeatUnixMs int64                  `protobuf:"varint,4,opt,name=last_heartbeat_unix_ms,json=lastHeartbeatUnixMs,proto3" json:"last_heartbeat_unix_ms,omitempty"`
	Draining            bool                   `protobuf:"varint,5,opt,name=draining,proto3" json:"draining,omitempty"`
	Healthy             bool                   `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_marshal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{3}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetCapacity() *ResourceSpec {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeInfo) GetAllocated() *ResourceSpec {
	if x != nil {
		return x.Allocated
	}
	return nil
}

func (x *NodeInfo) GetLastHeartbeatUnixMs() int64 {
	if x != nil {
		return x.LastHeartbeatUnixMs
	}
	return 0
}

func (x *NodeInfo) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

func (x *NodeInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *JobSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_marshal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitJobRequest) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_marshal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_marshal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_marshal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{7}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_marshal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{8}
}

func (x *CancelJobResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []string               `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_marshal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{9}
}

func (x *ListJobsRequest) GetStates() []string {
	if x != nil {
		return x.States
	}
	return nil
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_marshal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{10}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_marshal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{11}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_marshal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{12}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // empty = assign one
	AgentAddr     string                 `protobuf:"bytes,2,opt,name=agent_addr,json=agentAddr,proto3" json:"agent_addr,omitempty"` // host:port marshald dials back on
	Capacity      *ResourceSpec          `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_marshal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAgentAddr() string {
	if x != nil {
		return x.AgentAddr
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapacity() *ResourceSpec {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_marshal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentAddr     string                 `protobuf:"bytes,2,opt,name=agent_addr,json=agentAddr,proto3" json:"agent_addr,omitempty"`
	RunningTokens []string               `protobuf:"bytes,3,rep,name=running_tokens,json=runningTokens,proto3" json:"running_tokens,omitempty"` // tokens of attempts running on the node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_marshal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentAddr() string {
	if x != nil {
		return x.AgentAddr
	}
	return ""
}

func (x *HeartbeatRequest) GetRunningTokens() []string {
	if x != nil {
		return x.RunningTokens
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KillTokens    []string               `protobuf:"bytes,1,rep,name=kill_tokens,json=killTokens,proto3" json:"kill_tokens,omitempty"` // fenced-out attempts to kill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_marshal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatResponse) GetKillTokens() []string {
	if x != nil {
		return x.KillTokens
	}
	return nil
}

type ReportJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // jobID/attempt
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobRequest) Reset() {
	*x = ReportJobRequest{}
	mi := &file_marshal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobRequest) ProtoMessage() {}

func (x *ReportJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobRequest.ProtoReflect.Descriptor instead.
func (*ReportJobRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{17}
}

func (x *ReportJobRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReportJobRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportJobRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportJobRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobResponse) Reset() {
	*x = ReportJobResponse{}
	mi := &file_marshal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobResponse) ProtoMessage() {}

func (x *ReportJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobResponse.ProtoReflect.Descriptor instead.
func (*ReportJobResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{18}
}

type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Cmd           string                 `protobuf:"bytes,4,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Request       *ResourceSpec          `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_marshal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{19}
}

func (x *StartJobRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StartJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartJobRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StartJobRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *StartJobRequest) GetRequest() *ResourceSpec {
	if x != nil {
		return x.Request
	}
	return nil
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyKnown  bool                   `protobuf:"varint,1,opt,name=already_known,json=alreadyKnown,proto3" json:"already_known,omitempty"` // token was a duplicate; no new execution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_marshal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{20}
}

func (x *StartJobResponse) GetAlreadyKnown() bool {
	if x != nil {
		return x.AlreadyKnown
	}
	return false
}

type ProbeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTokenRequest) Reset() {
	*x = ProbeTokenRequest{}
	mi := &file_marshal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTokenRequest) ProtoMessage() {}

func (x *ProbeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTokenRequest.ProtoReflect.Descriptor instead.
func (*ProbeTokenRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{21}
}

func (x *ProbeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProbeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         bool                   `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	Finished      bool                   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTokenResponse) Reset() {
	*x = ProbeTokenResponse{}
	mi := &file_marshal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTokenResponse) ProtoMessage() {}

func (x *ProbeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTokenResponse.ProtoReflect.Descriptor instead.
func (*ProbeTokenResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{22}
}

func (x *ProbeTokenResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *ProbeTokenResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ProbeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type KillJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillJobRequest) Reset() {
	*x = KillJobRequest{}
	mi := &file_marshal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillJobRequest) ProtoMessage() {}

func (x *KillJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillJobRequest.ProtoReflect.Descriptor instead.
func (*KillJobRequest) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{23}
}

func (x *KillJobRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type KillJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasRunning    bool                   `protobuf:"varint,1,opt,name=was_running,json=wasRunning,proto3" json:"was_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillJobResponse) Reset() {
	*x = KillJobResponse{}
	mi := &file_marshal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillJobResponse) ProtoMessage() {}

func (x *KillJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillJobResponse.ProtoReflect.Descriptor instead.
func (*KillJobResponse) Descriptor() ([]byte, []int) {
	return file_marshal_proto_rawDescGZIP(), []int{24}
}

func (x *KillJobResponse) GetWasRunning() bool {
	if x != nil {
		return x.WasRunning
	}
	return false
}

var File_marshal_proto protoreflect.FileDescriptor

const file_marshal_proto_rawDesc = "" +
	"\n" +
	"\rmarshal.proto\x12\n" +
	"marshal.v1\"\xc1\x01\n" +
	"\fResourceSpec\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\x03R\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x126\n" +
	"\x04gres\x18\x03 \x03(\v2\".marshal.v1.ResourceSpec.GresEntryR\x04gres\x1a7\n" +
	"\tGresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc4\x01\n" +
	"\aJobSpec\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x122\n" +
	"\arequest\x18\x03 \x01(\v2\x18.marshal.v1.ResourceSpecR\arequest\x12\x1d\n" +
	"\n" +
	"node_count\x18\x04 \x01(\x05R\tnodeCount\x12$\n" +
	"\x0eest_runtime_ms\x18\x05 \x01(\x03R\festRuntimeMs\x12\x10\n" +
	"\x03cmd\x18\x06 \x01(\tR\x03cmd\"\xb8\x01\n" +
	"\aJobInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04spec\x18\x02 \x01(\v2\x13.marshal.v1.JobSpecR\x04spec\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12)\n" +
	"\x11submit_at_unix_ms\x18\x05 \x01(\x03R\x0esubmitAtUnixMs\x12\x19\n" +
	"\bnode_ids\x18\x06 \x03(\tR\anodeIds\"\xf3\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\bcapacity\x18\x02 \x01(\v2\x18.marshal.v1.ResourceSpecR\bcapacity\x126\n" +
	"\tallocated\x18\x03 \x01(\v2\x18.marshal.v1.ResourceSpecR\tallocated\x123\n" +
	"\x16last_heartbeat_unix_ms\x18\x04 \x01(\x03R\x13lastHeartbeatUnixMs\x12\x1a\n" +
	"\bdraining\x18\x05 \x01(\bR\bdraining\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\";\n" +
	"\x10SubmitJobRequest\x12'\n" +
	"\x04spec\x18\x01 \x01(\v2\x13.marshal.v1.JobSpecR\x04spec\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\")\n" +
	"\x11CancelJobResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\")\n" +
	"\x0fListJobsRequest\x12\x16\n" +
	"\x06states\x18\x01 \x03(\tR\x06states\";\n" +
	"\x10ListJobsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.marshal.v1.JobInfoR\x04jobs\"\x12\n" +
	"\x10ListNodesRequest\"?\n" +
	"\x11ListNodesResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.marshal.v1.NodeInfoR\x05nodes\"\x83\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"agent_addr\x18\x02 \x01(\tR\tagentAddr\x124\n" +
	"\bcapacity\x18\x03 \x01(\v2\x18.marshal.v1.ResourceSpecR\bcapacity\"/\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"q\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"agent_addr\x18\x02 \x01(\tR\tagentAddr\x12%\n" +
	"\x0erunning_tokens\x18\x03 \x03(\tR\rrunningTokens\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vkill_tokens\x18\x01 \x03(\tR\n" +
	"killTokens\"y\n" +
	"\x10ReportJobRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x13\n" +
	"\x11ReportJobResponse\"\x9e\x01\n" +
	"\x0fStartJobRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\tR\x03cmd\x122\n" +
	"\arequest\x18\x05 \x01(\v2\x18.marshal.v1.ResourceSpecR\arequest\"7\n" +
	"\x10StartJobResponse\x12#\n" +
	"\ralready_known\x18\x01 \x01(\bR\falreadyKnown\")\n" +
	"\x11ProbeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"`\n" +
	"\x12ProbeTokenResponse\x12\x14\n" +
	"\x05known\x18\x01 \x01(\bR\x05known\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"&\n" +
	"\x0eKillJobRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\x0fKillJobResponse\x12\x1f\n" +
	"\vwas_running\x18\x01 \x01(\bR\n" +
	"wasRunning2\xd4\x04\n" +
	"\fControlPlane\x12H\n" +
	"\tSubmitJob\x12\x1c.marshal.v1.SubmitJobRequest\x1a\x1d.marshal.v1.SubmitJobResponse\x128\n" +
	"\x06GetJob\x12\x19.marshal.v1.GetJobRequest\x1a\x13.marshal.v1.JobInfo\x12H\n" +
	"\tCancelJob\x12\x1c.marshal.v1.CancelJobRequest\x1a\x1d.marshal.v1.CancelJobResponse\x12E\n" +
	"\bListJobs\x12\x1b.marshal.v1.ListJobsRequest\x1a\x1c.marshal.v1.ListJobsResponse\x12H\n" +
	"\tListNodes\x12\x1c.marshal.v1.ListNodesRequest\x1a\x1d.marshal.v1.ListNodesResponse\x12Q\n" +
	"\fRegisterNode\x12\x1f.marshal.v1.RegisterNodeRequest\x1a .marshal.v1.RegisterNodeResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.marshal.v1.HeartbeatRequest\x1a\x1d.marshal.v1.HeartbeatResponse\x12H\n" +
	"\tReportJob\x12\x1c.marshal.v1.ReportJobRequest\x1a\x1d.marshal.v1.ReportJobResponse2\xdf\x01\n" +
	"\x05Agent\x12E\n" +
	"\bStartJob\x12\x1b.marshal.v1.StartJobRequest\x1a\x1c.marshal.v1.StartJobResponse\x12K\n" +
	"\n" +
	"ProbeToken\x12\x1d.marshal.v1.ProbeTokenRequest\x1a\x1e.marshal.v1.ProbeTokenResponse\x12B\n" +
	"\aKillJob\x12\x1a.marshal.v1.KillJobRequest\x1a\x1b.marshal.v1.KillJobResponseB0Z.github.com/AbhiDubz/Marshall/pkg/rpc/marshalpbb\x06proto3"

var (
	file_marshal_proto_rawDescOnce sync.Once
	file_marshal_proto_rawDescData []byte
)

func file_marshal_proto_rawDescGZIP() []byte {
	file_marshal_proto_rawDescOnce.Do(func() {
		file_marshal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marshal_proto_rawDesc), len(file_marshal_proto_rawDesc)))
	})
	return file_marshal_proto_rawDescData
}

var file_marshal_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_marshal_proto_goTypes = []any{
	(*ResourceSpec)(nil),         // 0: marshal.v1.ResourceSpec
	(*JobSpec)(nil),              // 1: marshal.v1.JobSpec
	(*JobInfo)(nil),              // 2: marshal.v1.JobInfo
	(*NodeInfo)(nil),             // 3: marshal.v1.NodeInfo
	(*SubmitJobRequest)(nil),     // 4: marshal.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),    // 5: marshal.v1.SubmitJobResponse
	(*GetJobRequest)(nil),        // 6: marshal.v1.GetJobRequest
	(*CancelJobRequest)(nil),     // 7: marshal.v1.CancelJobRequest
	(*CancelJobResponse)(nil),    // 8: marshal.v1.CancelJobResponse
	(*ListJobsRequest)(nil),      // 9: marshal.v1.ListJobsRequest
	(*ListJobsResponse)(nil),     // 10: marshal.v1.ListJobsResponse
	(*ListNodesRequest)(nil),     // 11: marshal.v1.ListNodesRequest
	(*ListNodesResponse)(nil),    // 12: marshal.v1.ListNodesResponse
	(*RegisterNodeRequest)(nil),  // 13: marshal.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 14: marshal.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),     // 15: marshal.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 16: marshal.v1.HeartbeatResponse
	(*ReportJobRequest)(nil),     // 17: marshal.v1.ReportJobRequest
	(*ReportJobResponse)(nil),    // 18: marshal.v1.ReportJobResponse
	(*StartJobRequest)(nil),      // 19: marshal.v1.StartJobRequest
	(*StartJobResponse)(nil),     // 20: marshal.v1.StartJobResponse
	(*ProbeTokenRequest)(nil),    // 21: marshal.v1.ProbeTokenRequest
	(*ProbeTokenResponse)(nil),   // 22: marshal.v1.ProbeTokenResponse
	(*KillJobRequest)(nil),       // 23: marshal.v1.KillJobRequest
	(*KillJobResponse)(nil),      // 24: marshal.v1.KillJobResponse
	nil,                          // 25: marshal.v1.ResourceSpec.GresEntry
}
var file_marshal_proto_depIdxs = []int32{
	25, // 0: marshal.v1.ResourceSpec.gres:type_name -> marshal.v1.ResourceSpec.GresEntry
	0,  // 1: marshal.v1.JobSpec.request:type_name -> marshal.v1.ResourceSpec
	1,  // 2: marshal.v1.JobInfo.spec:type_name -> marshal.v1.JobSpec
	0,  // 3: marshal.v1.NodeInfo.capacity:type_name -> marshal.v1.ResourceSpec
	0,  // 4: marshal.v1.NodeInfo.allocated:type_name -> marshal.v1.ResourceSpec
	1,  // 5: marshal.v1.SubmitJobRequest.spec:type_name -> marshal.v1.JobSpec
	2,  // 6: marshal.v1.ListJobsResponse.jobs:type_name -> marshal.v1.JobInfo
	3,  // 7: marshal.v1.ListNodesResponse.nodes:type_name -> marshal.v1.NodeInfo
	0,  // 8: marshal.v1.RegisterNodeRequest.capacity:type_name -> marshal.v1.ResourceSpec
	0,  // 9: marshal.v1.StartJobRequest.request:type_name -> marshal.v1.ResourceSpec
	4,  // 10: marshal.v1.ControlPlane.SubmitJob:input_type -> marshal.v1.SubmitJobRequest
	6,  // 11: marshal.v1.ControlPlane.GetJob:input_type -> marshal.v1.GetJobRequest
	7,  // 12: marshal.v1.ControlPlane.CancelJob:input_type -> marshal.v1.CancelJobRequest
	9,  // 13: marshal.v1.ControlPlane.ListJobs:input_type -> marshal.v1.ListJobsRequest
	11, // 14: marshal.v1.ControlPlane.ListNodes:input_type -> marshal.v1.ListNodesRequest
	13, // 15: marshal.v1.ControlPlane.RegisterNode:input_type -> marshal.v1.RegisterNodeRequest
	15, // 16: marshal.v1.ControlPlane.Heartbeat:input_type -> marshal.v1.HeartbeatRequest
	17, // 17: marshal.v1.ControlPlane.ReportJob:input_type -> marshal.v1.ReportJobRequest
	19, // 18: marshal.v1.Agent.StartJob:input_type -> marshal.v1.StartJobRequest
	21, // 19: marshal.v1.Agent.ProbeToken:input_type -> marshal.v1.ProbeTokenRequest
	23, // 20: marshal.v1.Agent.KillJob:input_type -> marshal.v1.KillJobRequest
	5,  // 21: marshal.v1.ControlPlane.SubmitJob:output_type -> marshal.v1.SubmitJobResponse
	2,  // 22: marshal.v1.ControlPlane.GetJob:output_type -> marshal.v1.JobInfo
	8,  // 23: marshal.v1.ControlPlane.CancelJob:output_type -> marshal.v1.CancelJobResponse
	10, // 24: marshal.v1.ControlPlane.ListJobs:output_type -> marshal.v1.ListJobsResponse
	12, // 25: marshal.v1.ControlPlane.ListNodes:output_type -> marshal.v1.ListNodesResponse
	14, // 26: marshal.v1.ControlPlane.RegisterNode:output_type -> marshal.v1.RegisterNodeResponse
	16, // 27: marshal.v1.ControlPlane.Heartbeat:output_type -> marshal.v1.HeartbeatResponse
	18, // 28: marshal.v1.ControlPlane.ReportJob:output_type -> marshal.v1.ReportJobResponse
	20, // 29: marshal.v1.Agent.StartJob:output_type -> marshal.v1.StartJobResponse
	22, // 30: marshal.v1.Agent.ProbeToken:output_type -> marshal.v1.ProbeTokenResponse
	24, // 31: marshal.v1.Agent.KillJob:output_type -> marshal.v1.KillJobResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_marshal_proto_init() }
func file_marshal_proto_init() {
	if File_marshal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marshal_proto_rawDesc), len(file_marshal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_marshal_proto_goTypes,
		DependencyIndexes: file_marshal_proto_depIdxs,
		MessageInfos:      file_marshal_proto_msgTypes,
	}.Build()
	File_marshal_proto = out.File
	file_marshal_proto_goTypes = nil
	file_marshal_proto_depIdxs = nil
}
